spring:
  application:
    name: frontend-eureka-client
server:
  port: 19211
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl.defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
